apiVersion: v1
kind: Service
metadata:
  labels:
    app: percona-galera
  name: percona-galera-lb
spec:
  type: LoadBalancer
  ports:
  - name: mysql
    port: 3306
  selector:
    app: percona-galera