apiVersion: v1
kind: Service
metadata:
  labels:
    app: percona-galera
  name: percona-galera-xtradb
spec:
  clusterIP: None
  ports:
  - name: galera-replication
    port: 4567
  - name: state-transfer
    port: 4568
  - name: state-snapshot
    port: 4444
  selector:
    app: percona-galera
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: percona-galera
  name: percona-galera
spec:
  #type: NodePort
  clusterIP: None
  ports:
  - name: mysql
    port: 3306
  selector:
    app: percona-galera
